{
 "title": "GreptimeDB Datanode",
 "description": "The Grafana dashboard of GreptimeDB datanode.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   {
    "name": "datanode",
    "query": {
     "query": "label_values(greptime_app_version{app=\"greptime-datanode\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Mito Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request QPS per Instance",
   "type": "timeseries",
   "description": "Request QPS per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, type) (rate(greptime_mito_handle_request_elapsed_count{instance=~\"$datanode\"}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{type}}]"
    }
   ]
  },
  {
   "title": "Request P99 per Instance",
   "type": "timeseries",
   "description": "Request P99 per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, pod, le, type) (rate(greptime_mito_handle_request_elapsed_bucket{instance=~\"$datanode\"}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{type}}]"
    }
   ]
  },
  {
   "title": "Write Buffer per Instance",
   "type": "timeseries",
   "description": "Write Buffer per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "greptime_mito_write_buffer_bytes{instance=~\"$datanode\"}",
     "legendFormat": "[{{instance}}]-[{{pod}}]"
    }
   ]
  },
  {
   "title": "Write Stall per Instance",
   "type": "timeseries",
   "description": "Write Stall per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance, pod) (greptime_mito_write_stall_total{instance=~\"$datanode\"})",
     "legendFormat": "[{{instance}}]-[{{pod}}]"
    }
   ]
  },
  {
   "title": "Flush QPS per Instance",
   "type": "timeseries",
   "description": "Flush QPS per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, reason) (rate(greptime_mito_flush_requests_total{instance=~\"$datanode\"}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{reason}}]"
    }
   ]
  },
  {
   "title": "Cached Bytes per Instance",
   "type": "timeseries",
   "description": "Cached Bytes per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "greptime_mito_cache_bytes{instance=~\"$datanode\"}",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{type}}]"
    }
   ]
  },
  {
   "title": "Read Stage QPS per Instance",
   "type": "timeseries",
   "description": "Read Stage QPS per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, pod) (rate(greptime_mito_read_stage_elapsed_count{instance=~\"$datanode\", stage=\"total\"}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]"
    }
   ]
  },
  {
   "title": "Read Stage P99 per Instance",
   "type": "timeseries",
   "description": "Read Stage P99 per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, pod, le, stage) (rate(greptime_mito_read_stage_elapsed_bucket{instance=~\"$datanode\"}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{stage}}]"
    }
   ]
  },
  {
   "title": "Compaction OPS per Instance",
   "type": "timeseries",
   "description": "Compaction OPS per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, pod) (rate(greptime_mito_compaction_total_elapsed_count{instance=~\"$datanode\"}[$__rate_interval]))",
     "legendFormat": "[{{ instance }}]-[{{pod}}]"
    }
   ]
  },
  {
   "title": "Compaction P99 per Instance",
   "type": "timeseries",
   "description": "Compaction P99 per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, pod, le) (rate(greptime_mito_compaction_total_elapsed_bucket{instance=~\"$datanode\"}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-compaction"
    }
   ]
  },
  {
   "title": "Write Stage P99 per Instance",
   "type": "timeseries",
   "description": "Write Stage P99 per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, pod, le, stage) (rate(greptime_mito_write_stage_elapsed_bucket{instance=~\"$datanode\"}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{stage}}]"
    }
   ]
  },
  { "title": "OpenDAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "QPS per Instance",
   "type": "timeseries",
   "description": "QPS per Instance.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, scheme, operation) (rate(opendal_operation_duration_seconds_count{instance=~\"$datanode\"}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]-[{{operation}}]"
    }
   ]
  },
  {
   "title": "Read QPS per Instance",
   "type": "timeseries",
   "description": "Read QPS per Instance.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, scheme) (rate(opendal_operation_duration_seconds_count{instance=~\"$datanode\", operation=\"read\"}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]"
    }
   ]
  },
  {
   "title": "Read P99 per Instance",
   "type": "timeseries",
   "description": "Read P99 per Instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, pod, le, scheme) (rate(opendal_operation_duration_seconds_bucket{instance=~\"$datanode\",operation=\"read\"}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-{{scheme}}"
    }
   ]
  },
  {
   "title": "Write QPS per Instance",
   "type": "timeseries",
   "description": "Write QPS per Instance.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, scheme) (rate(opendal_operation_duration_seconds_count{instance=~\"$datanode\", operation=\"write\"}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-{{scheme}}"
    }
   ]
  },
  {
   "title": "Write P99 per Instance",
   "type": "timeseries",
   "description": "Write P99 per Instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, pod, le, scheme) (rate(opendal_operation_duration_seconds_bucket{instance=~\"$datanode\", operation=\"write\"}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]"
    }
   ]
  },
  {
   "title": "List QPS per Instance",
   "type": "timeseries",
   "description": "List QPS per Instance.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, scheme) (rate(opendal_operation_duration_seconds_count{instance=~\"$datanode\", operation=\"list\"}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]"
    }
   ]
  },
  {
   "title": "List P99 per Instance",
   "type": "timeseries",
   "description": "List P99 per Instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, pod, le, scheme) (rate(opendal_operation_duration_seconds_bucket{instance=~\"$datanode\", operation=\"list\"}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]"
    }
   ]
  },
  {
   "title": "Other Requests per Instance",
   "type": "timeseries",
   "description": "Other Requests per Instance.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, scheme, operation) (rate(opendal_operation_duration_seconds_count{instance=~\"$datanode\",operation!~\"read|write|list|stat\"}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]-[{{operation}}]"
    }
   ]
  },
  {
   "title": "Other Request P99 per Instance",
   "type": "timeseries",
   "description": "Other Request P99 per Instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, pod, le, scheme, operation) (rate(opendal_operation_duration_seconds_bucket{instance=~\"$datanode\", operation!~\"read|write|list\"}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]-[{{operation}}]"
    }
   ]
  }
 ]
}