{
 "title": "GreptimeDB",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "greptime_app_version", "legendFormat": "{{short_version}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "greptime_catalog_schema_count", "legendFormat": "database" },
    {
     "expr": "greptime_table_operator_create_table_count",
     "legendFormat": "table"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_threads", "legendFormat": "threads" }
   ]
  },
  {
   "title": "Up",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "up{}", "legendFormat": "_" }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[2s]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Protocol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "gRPC insert elapsed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_frontend_handle_sql_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{label_name}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_frontend_handle_sql_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{label_name}}-p99"
    }
   ]
  },
  {
   "title": "PromStore write elasped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_http_prometheus_write_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{label_name}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_prometheus_write_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{label_name}}-p99"
    }
   ]
  },
  {
   "title": "HTTP PromQL elasped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_http_promql_instant_query_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "instant-{{label_name}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_promql_instant_query_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "instant-{{label_name}}-p99"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_promql_range_query_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "range-{{label_name}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_promql_range_query_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "range-{{label_name}}-p99"
    }
   ]
  },
  { "title": "Mito Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "handle request elapsed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, type, group) (rate(greptime_mito_handle_request_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{group}}-{{type}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, type, group) (rate(greptime_mito_handle_request_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{group}}-{{type}}-p99"
    }
   ]
  },
  {
   "title": "write rows total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(greptime_mito_write_rows_total[2s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mito engine read stage duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, stage) (rate(greptime_mito_read_stage_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write stage duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, stage) (rate(greptime_mito_write_stage_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{stage}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, stage) (rate(greptime_mito_write_stage_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{stage}}-p99"
    }
   ]
  },
  {
   "title": "flush / compaction count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "idelta(greptime_mito_compaction_stage_elapsed_count{stage=\"merge\"}[5m])",
     "legendFormat": "compaction-{{stage}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, type) (rate(greptime_mito_flush_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "flush-{{type}}"
    }
   ]
  },
  {
   "title": "flush / compaction count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "idelta(greptime_mito_flush_requests_total[2s])",
     "legendFormat": "flush-{{reason}}"
    },
    {
     "expr": "idelta(greptime_mito_compaction_requests_total[2s])",
     "legendFormat": "compaction"
    }
   ]
  },
  { "title": "Metric Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "metric engine to mito R/W duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(greptime_metric_engine_mito_op_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "p95-{{operation}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(greptime_metric_engine_mito_op_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "p99-{{label_name}}"
    }
   ]
  },
  {
   "title": "metric engine to mito DDL duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(greptime_metric_engine_mito_ddl_bucket[$__rate_interval])))",
     "legendFormat": "p95-{{operation}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(greptime_metric_engine_mito_ddl_bucket[$__rate_interval])))",
     "legendFormat": "p99-{{label_name}}"
    }
   ]
  },
  { "title": "Storage Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "raft engine sync count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(raft_engine_sync_log_duration_seconds_count[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "wal write size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(greptime_mito_read_row_groups_total[2s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "raft-engine sync duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, type) (rate(raft_engine_sync_log_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le, type) (rate(raft_engine_sync_log_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenDAL operation duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation, schema) (rate(opendal_requests_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "raft engine write duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, group) (rate(raft_engine_write_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{group}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, group) (rate(raft_engine_write_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{group}}-p99"
    }
   ]
  },
  {
   "title": "wal write size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(raft_engine_write_size_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}