name: Setup MySQL
description: Deploy MySQL on Docker or Kubernetes
inputs:
  provider:
    default: "docker"
    description: "Deployment provider: docker"

runs:
  using: composite
  steps:
  - name: Install MySQL
    shell: bash
    run: |
      if [ "${{ inputs.provider }}" != "docker" ]; then
        echo "Unsupported provider: ${{ inputs.provider }}"
        exit 1
      fi

      REPO_ROOT=$(git rev-parse --show-toplevel)
      "${REPO_ROOT}/.github/scripts/pull-test-deps-images.sh"
      docker compose -f "${REPO_ROOT}/tests-integration/fixtures/docker-compose.yml" up -d --wait mysql
