githubConfigUrl: "https://github.com/GreptimeTeam/greptimedb"
githubConfigSecret: greptimedb-arc-github-app

runnerScaleSetName: "perf-regression-8-cores"
minRunners: 0
maxRunners: 4

template:
  spec:
    containers:
      - name: runner
        image: greptime-registry.cn-hangzhou.cr.aliyuncs.com/greptime/greptimedb-query-regression-runner:latest
        imagePullPolicy: Always
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: "8"
            memory: 24Gi
            ephemeral-storage: 80Gi
          limits:
            cpu: "8"
            memory: 24Gi
            ephemeral-storage: 80Gi
