CREATE TABLE ato(i INTEGER, j TIMESTAMP TIME INDEX);

ALTER TABLE ato MODIFY OPTIONS 'ttl'='1d';

SHOW CREATE TABLE ato;

ALTER TABLE ato MODIFY OPTIONS 'ttl'='2d';

SHOW CREATE TABLE ato;

ALTER TABLE ato MODIFY OPTIONS 'ttl'=NULL;

SHOW CREATE TABLE ato;

DROP TABLE ato;