CREATE TABLE t(i INTEGER, j TIMESTAMP TIME INDEX);

DESC TABLE t;

ALTER TABLE t ADD COLUMN k INTEGER;

DESC TABLE t;

-- SQLNESS ARG restart=true
DESC TABLE t;

ALTER TABLE t ADD COLUMN m INTEGER;

DESC TABLE t;

INSERT INTO t VALUES (1, 2, 3, 4);

SELECT * FROM t;

ALTER TABLE t ADD COLUMN n INTEGER FIRST;

DESC TABLE t;

SELECT * FROM t;

INSERT INTO t VALUES (2, 3, 4, 5, 6);

ALTER TABLE t ADD COLUMN y INTEGER AFTER j;

DESC TABLE t;

SELECT * FROM t;

-- SQLNESS ARG restart=true
ALTER TABLE t ADD COLUMN a INTEGER FIRST;

DESC TABLE t;

ALTER TABLE t ADD COLUMN b INTEGER AFTER j;

DESC TABLE t;

SELECT * FROM t;

ALTER TABLE t ADD COLUMN x int xxx;

DROP TABLE t;
