CREATE TABLE test(id INTEGER PRIMARY KEY, i INTEGER NULL, j TIMESTAMP TIME INDEX, k BOOLEAN);

INSERT INTO test VALUES (1, 1, 1, false), (2, 2, 2, true);

ALTER TABLE test MODIFY "I" STRING;

ALTER TABLE test MODIFY k DATE;

ALTER TABLE test MODIFY id STRING;

ALTER TABLE test MODIFY j STRING;

ALTER TABLE test MODIFY I STRING;

SELECT * FROM test;

INSERT INTO test VALUES (3, "greptime", 3, true);

-- SQLNESS SORT_RESULT 3 1
SELECT * FROM test;

DESCRIBE test;

ALTER TABLE test MODIFY I INTEGER;

-- SQLNESS SORT_RESULT 3 1
SELECT * FROM test;

DESCRIBE test;

DROP TABLE test;
