CREATE TABLE test(id INTEGER PRIMARY KEY, i INTEGER NULL, j TIMESTAMP TIME INDEX, k BOOLEAN);

INSERT INTO test VALUES (1, 1, 1, false), (2, 2, 2, true);

ALTER TABLE test MODIFY COLUMN "I" STRING;

ALTER TABLE test MODIFY COLUMN k DATE;

ALTER TABLE test MODIFY COLUMN id STRING;

ALTER TABLE test MODIFY COLUMN j STRING;

ALTER TABLE test MODIFY COLUMN I STRING;

SELECT * FROM test;

INSERT INTO test VALUES (3, "greptime", 3, true);

-- SQLNESS SORT_RESULT 3 1
SELECT * FROM test;

DESCRIBE test;

ALTER TABLE test MODIFY COLUMN I INTEGER;

-- SQLNESS SORT_RESULT 3 1
SELECT * FROM test;

DESCRIBE test;

DROP TABLE test;
