CREATE TABLE test(i TIMESTAMP TIME INDEX, j INTEGER, k INTEGER NOT NULL);

INSERT INTO test VALUES (1, 1, 11), (2, 2, 12);

SELECT * FROM test;

ALTER TABLE test DROP COLUMN j;

-- SQLNESS REPLACE (region\s\d+\(\d+\,\s\d+\)) region
INSERT INTO test VALUES (3, NULL);

INSERT INTO test VALUES (3, 13);

SELECT * FROM test;

DROP TABLE test;
