CREATE TABLE test(i INTEGER, j TIMESTAMP TIME INDEX);

INSERT INTO test VALUES (1, 1), (2, 2);

ALTER TABLE test ALTER COLUMN "I" TYPE STRING;

ALTER TABLE test ALTER COLUMN I TYPE STRING;

SELECT * FROM test;

ALTER TABLE test ALTER COLUMN j TYPE STRING;

DESCRIBE test;

DROP TABLE test;