{
 "title": "GreptimeDB",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "greptime_app_version", "legendFormat": "{{short_version}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "greptime_catalog_schema_count", "legendFormat": "database" },
    {
     "expr": "greptime_table_operator_create_table_count",
     "legendFormat": "table"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_threads", "legendFormat": "threads" }
   ]
  },
  {
   "title": "Up",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "up{}", "legendFormat": "_" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Protocol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "HTTP query elapsed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_http_promql_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "promql-{{db}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_promql_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "promql-{{db}}-p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_http_sql_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "sql-{{db}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_sql_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "sql-{{db}}-p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_http_prometheus_read_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "promstore-read-{{db}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_prometheus_read_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "promstore-read-{{db}}-p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, db, method) (rate(greptime_servers_http_prometheus_promql_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "prom-promql-{{db}}-{{method}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db, method) (rate(greptime_servers_http_prometheus_promql_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "prom-promql-{{db}}-{{method}}-p99"
    }
   ]
  },
  {
   "title": "HTTP write elapsed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_http_influxdb_write_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "influx-{{db}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_influxdb_write_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "influx-{{db}}-p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_http_prometheus_write_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "promstore-{{db}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_prometheus_write_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "promstore-{{db}}-p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_http_otlp_metrics_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "otlp-metric-{{db}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_otlp_metrics_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "otlp-metric-{{db}}-p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_http_otlp_traces_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "otlp-trace-{{db}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_otlp_traces_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "otlp-trace-{{db}}-p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_http_logs_transform_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "log-transform-{{db}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_logs_transform_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "log-transform-{{db}}-p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_http_logs_ingestion_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "log-ingest-{{db}}-p99"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_http_logs_ingestion_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "log-ingest-{{db}}-p99"
    }
   ]
  },
  {
   "title": "HTTP request rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(path) (rate(greptime_servers_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs ingest rate (number of lines)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(db) (rate(greptime_servers_http_logs_ingestion_counter[$__rate_interval]))",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "gRPC insert elapsed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, db) (rate(greptime_servers_grpc_requests_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{db}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, db) (rate(greptime_servers_grpc_requests_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{db}}-p99"
    }
   ]
  },
  { "title": "Mito Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Handle request elapsed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, type) (rate(greptime_mito_handle_request_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{type}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, type) (rate(greptime_mito_handle_request_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{type}}-p99"
    }
   ]
  },
  {
   "title": "Write rows total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(greptime_mito_write_rows_total[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mito engine read stage duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, stage) (rate(greptime_mito_read_stage_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write stage duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, stage) (rate(greptime_mito_write_stage_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{stage}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, stage) (rate(greptime_mito_write_stage_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{stage}}-p99"
    }
   ]
  },
  {
   "title": "Flush / compaction duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "idelta(greptime_mito_compaction_stage_elapsed_count{stage=\"merge\"}[5m])",
     "legendFormat": "compaction-{{stage}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, type) (rate(greptime_mito_flush_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "flush-{{type}}"
    }
   ]
  },
  {
   "title": "Flush / compaction count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "idelta(greptime_mito_compaction_stage_elapsed_count{stage=\"merge\"}[5m])",
     "legendFormat": "compaction-{{stage}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, type) (rate(greptime_mito_flush_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "flush-{{type}}"
    }
   ]
  },
  {
   "title": "Write buffer size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "greptime_mito_write_buffer_bytes",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "greptime_mito_memtable_dict_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write stall count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "greptime_mito_write_stall_total",
     "legendFormat": "{{instance}}-worker-{{worker}}"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "greptime_mito_cache_bytes", "legendFormat": "{{instance}}-{{type}}" }
   ]
  },
  {
   "title": "Cache hit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(greptime_mito_cache_hit[$__rate_interval])) by (instance, type) / (sum(increase(greptime_mito_cache_miss[$__rate_interval])) by (instance, type) + sum(increase(greptime_mito_cache_hit[$__rate_interval])) by (instance, type))",
     "legendFormat": "{{instance}}-{{type}}"
    }
   ]
  },
  { "title": "Metric Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Metric engine to mito R/W duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(greptime_metric_engine_mito_op_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "p95-{{operation}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(greptime_metric_engine_mito_op_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "p99-{{operation}}"
    }
   ]
  },
  {
   "title": "Metric engine to mito DDL duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(greptime_metric_engine_mito_ddl_bucket[$__rate_interval])))",
     "legendFormat": "p95-{{operation}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(greptime_metric_engine_mito_ddl_bucket[$__rate_interval])))",
     "legendFormat": "p99-{{label_name}}"
    }
   ]
  },
  { "title": "Storage Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "OpenDAL traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(opendal_bytes_total_sum[$__rate_interval])",
     "legendFormat": "{{scheme}}-{{operation}}"
    }
   ]
  },
  {
   "title": "OpenDAL operation duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation, schema) (rate(opendal_requests_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Store op duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le,logstore,optype) (rate(greptime_logstore_op_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{logstore}}-{{optype}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le,logstore,optype) (rate(greptime_logstore_op_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "{{logstore}}-{{optype}}-p99"
    }
   ]
  },
  {
   "title": "Index elapsed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, type) (rate(greptime_index_apply_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "apply-{{type}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, type) (rate(greptime_index_apply_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "apply-{{type}}-p95"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, type) (rate(greptime_index_create_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "create-{{type}}-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, type) (rate(greptime_index_create_elapsed_bucket[$__rate_interval])))",
     "legendFormat": "create-{{type}}-p95"
    }
   ]
  },
  {
   "title": "WAL sync duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, type, node) (rate(raft_engine_sync_log_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{node}}-{{type}}-p99"
    }
   ]
  },
  {
   "title": "WAL write size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(raft_engine_write_size_bucket[$__rate_interval])))",
     "legendFormat": "req-size-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(raft_engine_write_size_bucket[$__rate_interval])))",
     "legendFormat": "req-size-p99"
    },
    {
     "expr": "rate(raft_engine_write_size_sum[$__rate_interval])",
     "legendFormat": "throughput"
    }
   ]
  }
 ]
}