{
 "title": "GreptimeDB-Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "greptime_pod", "query": { "query": "label_values(greptime_pod)" } }
  ]
 },
 "panels": [
  { "title": "Frontend Entry Middleware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gRPC middleware",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, path, code) (rate(greptime_servers_grpc_requests_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{path}}-{{code}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, path, code) (rate(greptime_servers_grpc_requests_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{path}}-{{code}}-qps"
    }
   ]
  },
  {
   "title": "HTTP middleware",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, path, method, code) (rate(greptime_servers_http_requests_elapsed_bucket{greptime_pod=~\"$greptime_pod\",path!~\"/health|/metrics\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{path}}-{{method}}-{{code}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, path, method, code) (rate(greptime_servers_http_requests_elapsed_count{greptime_pod=~\"$greptime_pod\",path!~\"/health|/metrics\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{path}}-{{method}}-{{code}}-qps"
    }
   ]
  },
  {
   "title": "MySQL per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, subprotocol, db) (rate(greptime_servers_mysql_query_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{subprotocol}}-{{db}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, subprotocol, db) (rate(greptime_servers_mysql_query_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{subprotocol}}-{{db}}-qps"
    }
   ]
  },
  {
   "title": "PostgreSQL per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, subprotocol, db) (rate(greptime_servers_postgres_query_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{subprotocol}}-{{db}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, subprotocol, db) (rate(greptime_servers_postgres_query_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{subprotocol}}-{{db}}-qps"
    }
   ]
  },
  { "title": "Frontend HTTP per DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP sql per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, db) (rate(greptime_servers_http_sql_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{db}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, db) (rate(greptime_servers_http_sql_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{db}}-qps"
    }
   ]
  },
  {
   "title": "HTTP promql per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, db) (rate(greptime_servers_http_promql_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{db}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, db) (rate(greptime_servers_http_promql_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{db}}-qps"
    }
   ]
  },
  {
   "title": "HTTP influxdb per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, db) (rate(greptime_servers_http_influxdb_write_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{db}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, db) (rate(greptime_servers_http_influxdb_write_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{db}}-qps"
    }
   ]
  },
  {
   "title": "HTTP prom store write per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, db) (rate(greptime_servers_http_prometheus_write_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{db}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, db) (rate(greptime_servers_http_prometheus_write_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{db}}-qps"
    }
   ]
  },
  {
   "title": "HTTP prom store read per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, db) (rate(greptime_servers_http_prometheus_read_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{db}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, db) (rate(greptime_servers_http_prometheus_read_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{db}}-qps"
    }
   ]
  },
  {
   "title": "HTTP otlp metrics per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, db) (rate(greptime_servers_http_otlp_metrics_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{db}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, db) (rate(greptime_servers_http_otlp_metrics_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{db}}-qps"
    }
   ]
  },
  {
   "title": "HTTP otlp traces per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, db) (rate(greptime_servers_http_otlp_traces_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{db}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, db) (rate(greptime_servers_http_otlp_traces_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{db}}-qps"
    }
   ]
  },
  { "title": "Frontend gRPC per DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "gRPC per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.99, sum by(greptime_pod, le, db, type, code) (rate(greptime_servers_grpc_db_request_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))), \"db\", \"$1\", \"db\", \"(.*)-public\")",
     "legendFormat": "{{greptime_pod}}-{{db}}-{{type}}-{{code}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, db, type, code) (rate(greptime_servers_grpc_db_request_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{db}}-{{type}}-{{code}}-qps"
    }
   ]
  },
  {
   "title": "gRPC prom per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, db) (rate(greptime_servers_grpc_prom_request_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{db}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, db) (rate(greptime_servers_grpc_prom_request_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{db}}-qps"
    }
   ]
  },
  { "title": "Frontend-Datanode Call", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "ingested rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(greptime_table_operator_ingest_rows{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])",
     "legendFormat": "{{greptime_pod}}-rps"
    }
   ]
  },
  {
   "title": "gRPC region call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, request_type) (rate(greptime_grpc_region_request_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{request_type}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, request_type) (rate(greptime_grpc_region_request_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{request_type}}-qps"
    }
   ]
  },
  { "title": "Datanode Mito", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "handle request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, type) (rate(greptime_mito_handle_request_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{type}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, type) (rate(greptime_mito_handle_request_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{type}}-qps"
    }
   ]
  },
  {
   "title": "Write buffer bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "greptime_mito_write_buffer_bytes{greptime_pod=~\"$greptime_pod\"}",
     "legendFormat": "{{greptime_pod}}"
    }
   ]
  },
  {
   "title": "flush total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(greptime_pod, reason) (rate(greptime_mito_flush_requests_total{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{reason}}-success"
    },
    {
     "expr": "sum by(greptime_pod, reason) (rate(greptime_mito_flush_errors_total{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{reason}}-error"
    },
    {
     "expr": "sum by(greptime_pod) (rate(greptime_mito_flush_bytes_total{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-bytes"
    }
   ]
  },
  {
   "title": "write stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, stage) (rate(greptime_mito_write_stage_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{stage}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, stage) (rate(greptime_mito_write_stage_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{stage}}-qps"
    }
   ]
  },
  {
   "title": "compaction total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le) (rate(greptime_mito_compaction_total_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-p99"
    },
    {
     "expr": "sum by(greptime_pod) (rate(greptime_mito_compaction_total_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-qps"
    }
   ]
  },
  {
   "title": "compaction stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, stage) (rate(greptime_mito_compaction_stage_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{stage}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, stage) (rate(greptime_mito_compaction_stage_elapsed_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{stage}}-qps"
    }
   ]
  },
  {
   "title": "write stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, stage) (rate(greptime_mito_read_stage_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{stage}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, stage) (rate(greptime_mito_read_stage_elapsed_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{stage}}-qps"
    }
   ]
  },
  {
   "title": "cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "greptime_mito_cache_bytes{greptime_pod=~\"$greptime_pod\"}",
     "legendFormat": "{{greptime_pod}}"
    }
   ]
  },
  {
   "title": "cache hit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "greptime_mito_cache_hit{greptime_pod=~\"$greptime_pod\"} / (greptime_mito_cache_hit{greptime_pod=~\"$greptime_pod\"} + greptime_mito_cache_miss{greptime_pod=~\"$greptime_pod\"})",
     "legendFormat": "{{greptime_pod}}-{{type}}"
    }
   ]
  },
  { "title": "OpenDAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "requests_duration_seconds_READ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, scheme) (rate(opendal_requests_duration_seconds_bucket{greptime_pod=~\"$greptime_pod\",operation=\"read\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, scheme) (rate(opendal_requests_duration_seconds_count{greptime_pod=~\"$greptime_pod\", operation=\"read\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-qps"
    }
   ]
  },
  {
   "title": "requests_duration_seconds_WRITE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, scheme) (rate(opendal_requests_duration_seconds_bucket{greptime_pod=~\"$greptime_pod\", operation=\"write\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, scheme) (rate(opendal_requests_duration_seconds_count{greptime_pod=~\"$greptime_pod\", operation=\"write\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-qps"
    }
   ]
  },
  {
   "title": "requests_duration_seconds_LIST",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, scheme) (rate(opendal_requests_duration_seconds_bucket{greptime_pod=~\"$greptime_pod\", operation=\"list\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, scheme) (rate(opendal_requests_duration_seconds_count{greptime_pod=~\"$greptime_pod\", operation=\"list\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-qps"
    }
   ]
  },
  {
   "title": "requests_duration_seconds_STAT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, scheme) (rate(opendal_requests_duration_seconds_bucket{greptime_pod=~\"$greptime_pod\", operation=\"stat\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, scheme) (rate(opendal_requests_duration_seconds_count{greptime_pod=~\"$greptime_pod\", operation=\"stat\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-qps"
    }
   ]
  },
  {
   "title": "requests_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, scheme, operation) (rate(opendal_requests_duration_seconds_bucket{greptime_pod=~\"$greptime_pod\", operation!~\"read|write|list\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-{{operation}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, scheme, operation) (rate(opendal_requests_duration_seconds_count{greptime_pod=~\"$greptime_pod\", operation!~\"read|write|list\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-{{operation}}-qps"
    }
   ]
  },
  {
   "title": "bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(greptime_pod, le, scheme, operation) (rate(opendal_bytes_total_bucket{greptime_pod=~\"$greptime_pod\"}[$__rate_interval])))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-{{operation}}-p99"
    },
    {
     "expr": "sum by(greptime_pod, scheme, operation) (rate(opendal_bytes_total_count{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-{{operation}}-bytes"
    }
   ]
  },
  {
   "title": "requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(greptime_pod, scheme, operation) (rate(opendal_requests_total{greptime_pod=~\"$greptime_pod\"}[$__rate_interval]))",
     "legendFormat": "{{greptime_pod}}-{{scheme}}-{{operation}}-qps"
    }
   ]
  }
 ]
}