-- Dynamic Filter Test: Hash Join
-- Tests dynamic filters generated by hash join

-- Test 1.1: Basic Hash Join
CREATE TABLE orders ("id" INT, customer_id INT, amount DOUBLE, ts TIMESTAMP TIME INDEX);
CREATE TABLE customers (customer_id INT, "name" STRING, tier STRING, ts TIMESTAMP TIME INDEX);

-- Insert sufficient test data
INSERT INTO orders VALUES
  (1, 1, 100.0, '2024-01-01 00:00:00'),
  (2, 2, 200.0, '2024-01-02 00:00:00'),
  (3, 1, 150.0, '2024-01-03 00:00:00');
-- Insert more rows to trigger dynamic filter

INSERT INTO customers VALUES
  (1, 'Alice', 'gold', '2024-01-01 00:00:00'),
  (2, 'Bob', 'silver', '2024-01-02 00:00:00');

-- Test: Basic hash join should produce dynamic filter
-- The hash join will build hash table from customers (small table)
-- and probe with orders (larger table), potentially using dynamic filter
EXPLAIN SELECT o."id", o.amount, c."name", c.tier
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
WHERE c.tier = 'gold';

-- SQLNESS REPLACE (-+) -
-- SQLNESS REPLACE (\s\s+) _
-- SQLNESS REPLACE (peers.*) REDACTED
-- SQLNESS REPLACE (metrics.*) REDACTED
EXPLAIN ANALYZE SELECT o."id", o.amount, c."name", c.tier
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
WHERE c.tier = 'gold';

-- Verify correctness
-- SQLNESS SORT_RESULT
SELECT o."id", o.amount, c."name", c.tier
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
WHERE c.tier = 'gold';

DROP TABLE orders;
DROP TABLE customers;

-- Test 1.2: Hash Join with Projection Alias
CREATE TABLE orders ("id" INT, customer_id INT, amount DOUBLE, ts TIMESTAMP TIME INDEX);
CREATE TABLE customers (customer_id INT, "name" STRING, tier STRING, ts TIMESTAMP TIME INDEX);

-- Insert test data
INSERT INTO orders VALUES
  (1, 1, 100.0, '2024-01-01 00:00:00'),
  (2, 2, 200.0, '2024-01-02 00:00:00'),
  (3, 1, 150.0, '2024-01-03 00:00:00'),
  (4, 3, 300.0, '2024-01-04 00:00:00');

INSERT INTO customers VALUES
  (1, 'Alice', 'gold', '2024-01-01 00:00:00'),
  (2, 'Bob', 'silver', '2024-01-02 00:00:00'),
  (3, 'Charlie', 'bronze', '2024-01-03 00:00:00');

-- Test: Hash join with projection alias
-- The alias on customer_id tests that dynamic filter correctly handles column references
EXPLAIN SELECT o."id", o.amount, c."name", c.tier
FROM (SELECT "id", customer_id as cid, amount, ts FROM orders) o
JOIN customers c ON o.cid = c.customer_id
WHERE c.tier IN ('gold', 'silver');

-- SQLNESS REPLACE (-+) -
-- SQLNESS REPLACE (\s\s+) _
-- SQLNESS REPLACE (peers.*) REDACTED
-- SQLNESS REPLACE (metrics.*) REDACTED
EXPLAIN ANALYZE SELECT o."id", o.amount, c."name", c.tier
FROM (SELECT "id", customer_id as cid, amount, ts FROM orders) o
JOIN customers c ON o.cid = c.customer_id
WHERE c.tier IN ('gold', 'silver');

-- Verify correctness
-- SQLNESS SORT_RESULT
SELECT o."id", o.amount, c."name", c.tier
FROM (SELECT "id", customer_id as cid, amount, ts FROM orders) o
JOIN customers c ON o.cid = c.customer_id
WHERE c.tier IN ('gold', 'silver');

DROP TABLE orders;
DROP TABLE customers;
