CREATE TABLE integers(i BIGINT TIME INDEX);

INSERT INTO integers VALUES (1), (2), (3);

EXPLAIN SELECT DISTINCT i%2 FROM integers ORDER BY 1;

DROP TABLE integers;


CREATE TABLE test (a INTEGER, b INTEGER, t BIGINT TIME INDEX);

INSERT INTO test VALUES (11, 22, 1), (13, 22, 2), (11, 21, 3), (11, 22, 4);

EXPLAIN SELECT a, b FROM test ORDER BY a, b;

EXPLAIN SELECT DISTINCT a, b FROM test ORDER BY a, b;

DROP TABLE test;
