SHOW CHARACTER SET;

SHOW CHARSET;

SHOW CHARACTER SET LIKE 'utf8';

SHOW CHARACTER SET LIKE 'latin1';

SHOW CHARSET LIKE 'utf8';

SHOW CHARACTER SET WHERE Charset = 'utf8';

SHOW CHARSET WHERE Charset = 'utf8';

SHOW CHARSET WHERE Charset = 'latin1';
