{
 "title": "GreptimeDB",
 "description": "The Grafana dashboards for GreptimeDB.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "information_schema", "query": "mysql" },
   {
    "name": "datanode",
    "query": {
     "query": "label_values(greptime_app_version{app=\"greptime-datanode\"},instance)"
    }
   },
   {
    "name": "frontend",
    "query": {
     "query": "label_values(greptime_app_version{app=\"greptime-frontend\"},instance)"
    }
   },
   {
    "name": "metasrv",
    "query": {
     "query": "label_values(greptime_app_version{app=\"greptime-metasrv\"},instance)"
    }
   },
   {
    "name": "flownode",
    "query": {
     "query": "label_values(greptime_app_version{app=\"greptime-flownode\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The start time of GreptimeDB.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "GreptimeDB version.",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT pkg_version FROM information_schema.build_info"
    }
   ]
  },
  {
   "title": "Total Ingestion Rate",
   "type": "stat",
   "description": "Total ingestion rate.",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(greptime_table_operator_ingest_rows[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Storage Size",
   "type": "stat",
   "description": "Total number of data file size.",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "select SUM(disk_size) from information_schema.region_statistics;"
    }
   ]
  },
  {
   "title": "Total Rows",
   "type": "stat",
   "description": "Total number of data rows in the cluster. Calculated by sum of rows from each region.",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "select SUM(region_rows) from information_schema.region_statistics;"
    }
   ]
  },
  {
   "title": "Deployment",
   "type": "stat",
   "description": "The deployment topology of GreptimeDB.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT count(*) as datanode FROM information_schema.cluster_info WHERE peer_type = 'DATANODE';"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT count(*) as frontend FROM information_schema.cluster_info WHERE peer_type = 'FRONTEND';"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT count(*) as metasrv FROM information_schema.cluster_info WHERE peer_type = 'METASRV';"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT count(*) as flownode FROM information_schema.cluster_info WHERE peer_type = 'FLOWNODE';"
    }
   ]
  },
  {
   "title": "Database Resources",
   "type": "stat",
   "description": "The number of the key resources in GreptimeDB.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT COUNT(*) as databases FROM information_schema.schemata WHERE schema_name NOT IN ('greptime_private', 'information_schema')"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT COUNT(*) as tables FROM information_schema.tables WHERE table_schema != 'information_schema'"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT COUNT(region_id) as regions FROM information_schema.region_peers"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT COUNT(*) as flows FROM information_schema.flows"
    }
   ]
  },
  {
   "title": "Data Size",
   "type": "stat",
   "description": "The data size of wal/index/manifest in the GreptimeDB.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT SUM(memtable_size) * 0.42825 as WAL FROM information_schema.region_statistics;\n"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT SUM(index_size) as index FROM information_schema.region_statistics;\n"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT SUM(manifest_size) as manifest FROM information_schema.region_statistics;\n"
    }
   ]
  },
  {
   "title": "Ingestion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Ingestion Rate",
     "type": "timeseries",
     "description": "Total ingestion rate.\n\nHere we listed 3 primary protocols:\n\n- Prometheus remote write\n- Greptime's gRPC API (when using our ingest SDK)\n- Log ingestion http API\n",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "rowsps" } },
     "targets": [
      {
       "expr": "sum(rate(greptime_table_operator_ingest_rows{}[$__rate_interval]))",
       "legendFormat": "ingestion"
      }
     ]
    },
    {
     "title": "Ingestion Rate by Type",
     "type": "timeseries",
     "description": "Total ingestion rate.\n\nHere we listed 3 primary protocols:\n\n- Prometheus remote write\n- Greptime's gRPC API (when using our ingest SDK)\n- Log ingestion http API\n",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 392 },
     "fieldConfig": { "defaults": { "unit": "rowsps" } },
     "targets": [
      {
       "expr": "sum(rate(greptime_servers_http_logs_ingestion_counter[$__rate_interval]))",
       "legendFormat": "http-logs"
      },
      {
       "expr": "sum(rate(greptime_servers_prometheus_remote_write_samples[$__rate_interval]))",
       "legendFormat": "prometheus-remote-write"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Query Rate",
     "type": "timeseries",
     "description": "Total rate of query API calls by protocol. This metric is collected from frontends.\n\nHere we listed 3 main protocols:\n- MySQL\n- Postgres\n- Prometheus API\n\nNote that there are some other minor query APIs like /sql are not included",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 407 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (rate(greptime_servers_mysql_query_elapsed_count{}[$__rate_interval]))",
       "legendFormat": "mysql"
      },
      {
       "expr": "sum (rate(greptime_servers_postgres_query_elapsed_count{}[$__rate_interval]))",
       "legendFormat": "pg"
      },
      {
       "expr": "sum (rate(greptime_servers_http_promql_elapsed_counte{}[$__rate_interval]))",
       "legendFormat": "promql"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datanode Memory per Instance",
     "type": "timeseries",
     "description": "Current memory usage by instance",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{}) by (instance, pod)",
       "legendFormat": "[{{instance}}]-[{{ pod }}]"
      }
     ]
    },
    {
     "title": "Datanode CPU Usage per Instance",
     "type": "timeseries",
     "description": "Current cpu usage by instance",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{}[$__rate_interval]) * 1000) by (instance, pod)",
       "legendFormat": "[{{ instance }}]-[{{ pod }}]"
      }
     ]
    },
    {
     "title": "Frontend Memory per Instance",
     "type": "timeseries",
     "description": "Current memory usage by instance",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{}) by (instance, pod)",
       "legendFormat": "[{{ instance }}]-[{{ pod }}]"
      }
     ]
    },
    {
     "title": "Frontend CPU Usage per Instance",
     "type": "timeseries",
     "description": "Current cpu usage by instance",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{}[$__rate_interval]) * 1000) by (instance, pod)",
       "legendFormat": "[{{ instance }}]-[{{ pod }}]-cpu"
      }
     ]
    },
    {
     "title": "Metasrv Memory per Instance",
     "type": "timeseries",
     "description": "Current memory usage by instance",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{}) by (instance, pod)",
       "legendFormat": "[{{ instance }}]-[{{ pod }}]-resident"
      }
     ]
    },
    {
     "title": "Metasrv CPU Usage per Instance",
     "type": "timeseries",
     "description": "Current cpu usage by instance",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{}[$__rate_interval]) * 1000) by (instance, pod)",
       "legendFormat": "[{{ instance }}]-[{{ pod }}]"
      }
     ]
    },
    {
     "title": "Flownode Memory per Instance",
     "type": "timeseries",
     "description": "Current memory usage by instance",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{}) by (instance, pod)",
       "legendFormat": "[{{ instance }}]-[{{ pod }}]"
      }
     ]
    },
    {
     "title": "Flownode CPU Usage per Instance",
     "type": "timeseries",
     "description": "Current cpu usage by instance",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{}[$__rate_interval]) * 1000) by (instance, pod)",
       "legendFormat": "[{{ instance }}]-[{{ pod }}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP QPS per Instance",
     "type": "timeseries",
     "description": "HTTP QPS per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 325 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, path, method, code) (rate(greptime_servers_http_requests_elapsed_count{path!~\"/health|/metrics\"}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{path}}]-[{{method}}]-[{{code}}]"
      }
     ]
    },
    {
     "title": "HTTP P99 per Instance",
     "type": "timeseries",
     "description": "HTTP P99 per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 325 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le, path, method, code) (rate(greptime_servers_http_requests_elapsed_bucket{path!~\"/health|/metrics\"}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{path}}]-[{{method}}]-[{{code}}]-p99"
      }
     ]
    },
    {
     "title": "gRPC QPS per Instance",
     "type": "timeseries",
     "description": "gRPC QPS per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 333 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, path, code) (rate(greptime_servers_grpc_requests_elapsed_count{}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{path}}]-[{{code}}]"
      }
     ]
    },
    {
     "title": "gRPC P99 per Instance",
     "type": "timeseries",
     "description": "gRPC P99 per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 333 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le, path, code) (rate(greptime_servers_grpc_requests_elapsed_bucket{}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{path}}]-[{{method}}]-[{{code}}]-p99"
      }
     ]
    },
    {
     "title": "MySQL QPS per Instance",
     "type": "timeseries",
     "description": "MySQL QPS per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 341 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(pod, instance)(rate(greptime_servers_mysql_query_elapsed_count{}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]"
      }
     ]
    },
    {
     "title": "MySQL P99 per Instance",
     "type": "timeseries",
     "description": "MySQL P99 per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 341 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(pod, instance, le) (rate(greptime_servers_mysql_query_elapsed_bucket{}[$__rate_interval])))",
       "legendFormat": "[{{ instance }}]-[{{ pod }}]-p99"
      }
     ]
    },
    {
     "title": "PostgreSQL QPS per Instance",
     "type": "timeseries",
     "description": "PostgreSQL QPS per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 349 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(pod, instance)(rate(greptime_servers_postgres_query_elapsed_count{}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]"
      }
     ]
    },
    {
     "title": "PostgreSQL P99 per Instance",
     "type": "timeseries",
     "description": "PostgreSQL P99 per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 349 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(pod,instance,le) (rate(greptime_servers_postgres_query_elapsed_bucket{}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend to Datanode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingest Rows per Instance",
     "type": "timeseries",
     "description": "Ingestion rate by row as in each frontend",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "rowsps" } },
     "targets": [
      {
       "expr": "sum by(instance, pod)(rate(greptime_table_operator_ingest_rows{}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]"
      }
     ]
    },
    {
     "title": "Region Call QPS per Instance",
     "type": "timeseries",
     "description": "Region Call QPS per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, request_type) (rate(greptime_grpc_region_request_count{}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{request_type}}]"
      }
     ]
    },
    {
     "title": "Region Call P99 per Instance",
     "type": "timeseries",
     "description": "Region Call P99 per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le, request_type) (rate(greptime_grpc_region_request_bucket{}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{request_type}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Mito Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request OPS per Instance",
     "type": "timeseries",
     "description": "Request QPS per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, type) (rate(greptime_mito_handle_request_elapsed_count{}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{type}}]"
      }
     ]
    },
    {
     "title": "Request P99 per Instance",
     "type": "timeseries",
     "description": "Request P99 per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le, type) (rate(greptime_mito_handle_request_elapsed_bucket{}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{type}}]"
      }
     ]
    },
    {
     "title": "Write Buffer per Instance",
     "type": "timeseries",
     "description": "Write Buffer per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "greptime_mito_write_buffer_bytes{}",
       "legendFormat": "[{{instance}}]-[{{pod}}]"
      }
     ]
    },
    {
     "title": "Write Rows per Instance",
     "type": "timeseries",
     "description": "Ingestion size by row counts.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "rowsps" } },
     "targets": [
      {
       "expr": "sum by (instance, pod) (rate(greptime_mito_write_rows_total{}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]"
      }
     ]
    },
    {
     "title": "Flush OPS per Instance",
     "type": "timeseries",
     "description": "Flush QPS per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, reason) (rate(greptime_mito_flush_requests_total{}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{reason}}]"
      }
     ]
    },
    {
     "title": "Write Stall per Instance",
     "type": "timeseries",
     "description": "Write Stall per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(instance, pod) (greptime_mito_write_stall_total{})",
       "legendFormat": "[{{instance}}]-[{{pod}}]"
      }
     ]
    },
    {
     "title": "Read Stage OPS per Instance",
     "type": "timeseries",
     "description": "Read Stage OPS per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(instance, pod) (rate(greptime_mito_read_stage_elapsed_count{ stage=\"total\"}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]"
      }
     ]
    },
    {
     "title": "Read Stage P99 per Instance",
     "type": "timeseries",
     "description": "Read Stage P99 per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le, stage) (rate(greptime_mito_read_stage_elapsed_bucket{}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{stage}}]"
      }
     ]
    },
    {
     "title": "Write Stage P99 per Instance",
     "type": "timeseries",
     "description": "Write Stage P99 per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le, stage) (rate(greptime_mito_write_stage_elapsed_bucket{}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{stage}}]"
      }
     ]
    },
    {
     "title": "Compaction OPS per Instance",
     "type": "timeseries",
     "description": "Compaction OPS per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(instance, pod) (rate(greptime_mito_compaction_total_elapsed_count{}[$__rate_interval]))",
       "legendFormat": "[{{ instance }}]-[{{pod}}]"
      }
     ]
    },
    {
     "title": "Compaction P99 per Instance by Stage",
     "type": "timeseries",
     "description": "Compaction latency by stage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le, stage) (rate(greptime_mito_compaction_stage_elapsed_bucket{}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{stage}}]-p99"
      }
     ]
    },
    {
     "title": "Compaction P99 per Instance",
     "type": "timeseries",
     "description": "Compaction P99 per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le,stage) (rate(greptime_mito_compaction_total_elapsed_bucket{}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{stage}}]-compaction"
      }
     ]
    },
    {
     "title": "WAL write size",
     "type": "timeseries",
     "description": "Write-ahead logs write size as bytes. This chart includes stats of p95 and p99 size by instance, total WAL write rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le,instance, pod) (rate(raft_engine_write_size_bucket[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-req-size-p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le,instance,pod) (rate(raft_engine_write_size_bucket[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-req-size-p99"
      },
      {
       "expr": "sum by (instance, pod)(rate(raft_engine_write_size_sum[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-throughput"
      }
     ]
    },
    {
     "title": "Cached Bytes per Instance",
     "type": "timeseries",
     "description": "Cached Bytes per Instance.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "greptime_mito_cache_bytes{}",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{type}}]"
      }
     ]
    },
    {
     "title": "Inflight Compaction",
     "type": "timeseries",
     "description": "Ongoing compaction task count",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "greptime_mito_inflight_compaction_count",
       "legendFormat": "[{{instance}}]-[{{pod}}]"
      }
     ]
    },
    {
     "title": "WAL sync duration seconds",
     "type": "timeseries",
     "description": "Raft engine (local disk) log store sync latency, p99",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, type, node, instance, pod) (rate(raft_engine_sync_log_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-p99"
      }
     ]
    },
    {
     "title": "Log Store op duration seconds",
     "type": "timeseries",
     "description": "Write-ahead log operations latency at p99",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le,logstore,optype,instance, pod) (rate(greptime_logstore_op_elapsed_bucket[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{logstore}}]-[{{optype}}]-p99"
      }
     ]
    },
    {
     "title": "Inflight Flush",
     "type": "timeseries",
     "description": "Ongoing flush task count",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "greptime_mito_inflight_flush_count",
       "legendFormat": "[{{instance}}]-[{{pod}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenDAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS per Instance",
     "type": "timeseries",
     "description": "QPS per Instance.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, scheme, operation) (rate(opendal_operation_duration_seconds_count{}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]-[{{operation}}]"
      }
     ]
    },
    {
     "title": "Read QPS per Instance",
     "type": "timeseries",
     "description": "Read QPS per Instance.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, scheme) (rate(opendal_operation_duration_seconds_count{ operation=\"read\"}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]"
      }
     ]
    },
    {
     "title": "Read P99 per Instance",
     "type": "timeseries",
     "description": "Read P99 per Instance.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le, scheme) (rate(opendal_operation_duration_seconds_bucket{operation=\"read\"}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-{{scheme}}"
      }
     ]
    },
    {
     "title": "Write QPS per Instance",
     "type": "timeseries",
     "description": "Write QPS per Instance.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, scheme) (rate(opendal_operation_duration_seconds_count{ operation=\"write\"}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-{{scheme}}"
      }
     ]
    },
    {
     "title": "Write P99 per Instance",
     "type": "timeseries",
     "description": "Write P99 per Instance.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le, scheme) (rate(opendal_operation_duration_seconds_bucket{ operation=\"write\"}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]"
      }
     ]
    },
    {
     "title": "List QPS per Instance",
     "type": "timeseries",
     "description": "List QPS per Instance.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, scheme) (rate(opendal_operation_duration_seconds_count{ operation=\"list\"}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]"
      }
     ]
    },
    {
     "title": "List P99 per Instance",
     "type": "timeseries",
     "description": "List P99 per Instance.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le, scheme) (rate(opendal_operation_duration_seconds_bucket{ operation=\"list\"}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]"
      }
     ]
    },
    {
     "title": "Other Requests per Instance",
     "type": "timeseries",
     "description": "Other Requests per Instance.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, scheme, operation) (rate(opendal_operation_duration_seconds_count{operation!~\"read|write|list|stat\"}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]-[{{operation}}]"
      }
     ]
    },
    {
     "title": "Other Request P99 per Instance",
     "type": "timeseries",
     "description": "Other Request P99 per Instance.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(instance, pod, le, scheme, operation) (rate(opendal_operation_duration_seconds_bucket{ operation!~\"read|write|list\"}[$__rate_interval])))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]-[{{operation}}]"
      }
     ]
    },
    {
     "title": "Opendal traffic",
     "type": "timeseries",
     "description": "Total traffic as in bytes by instance and operation",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, scheme, operation) (rate(opendal_operation_bytes_sum{}[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{scheme}}]-[{{operation}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Metasrv",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Region migration datanode",
     "type": "state-timeline",
     "description": "Counter of region migration by source and destination",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "greptime_meta_region_migration_stat{datanode_type=\"src\"}",
       "legendFormat": "from-datanode-{{datanode_id}}"
      },
      {
       "expr": "greptime_meta_region_migration_stat{datanode_type=\"desc\"}",
       "legendFormat": "to-datanode-{{datanode_id}}"
      }
     ]
    },
    {
     "title": "Region migration error",
     "type": "timeseries",
     "description": "Counter of region migration error",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "greptime_meta_region_migration_error",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Datanode load",
     "type": "timeseries",
     "description": "Gauge of load information of each datanode, collected via heartbeat between datanode and metasrv. This information is for metasrv to schedule workloads.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "greptime_datanode_load", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Flownode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow Ingest / Output Rate",
     "type": "timeseries",
     "description": "Flow Ingest / Output Rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by(instance, pod, direction) (rate(greptime_flow_processed_rows[$__rate_interval]))",
       "legendFormat": "[{{pod}}]-[{{instance}}]-[{{direction}}]"
      }
     ]
    },
    {
     "title": "Flow Ingest Latency",
     "type": "timeseries",
     "description": "Flow Ingest Latency.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(greptime_flow_insert_elapsed_bucket[$__rate_interval])) by (le, instance, pod))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(greptime_flow_insert_elapsed_bucket[$__rate_interval])) by (le, instance, pod))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-p99"
      }
     ]
    },
    {
     "title": "Flow Operation Latency",
     "type": "timeseries",
     "description": "Flow Operation Latency.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(greptime_flow_processing_time_bucket[$__rate_interval])) by (le,instance,pod,type))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{type}}]-p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(greptime_flow_processing_time_bucket[$__rate_interval])) by (le,instance,pod,type))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{type}}]-p99"
      }
     ]
    },
    {
     "title": "Flow Buffer Size per Instance",
     "type": "timeseries",
     "description": "Flow Buffer Size per Instance.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 26 },
     "targets": [
      { "expr": "greptime_flow_input_buf_size", "legendFormat": "[{{instance}}]-[{{pod}]" }
     ]
    },
    {
     "title": "Flow Processing Error per Instance",
     "type": "timeseries",
     "description": "Flow Processing Error per Instance.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
     "targets": [
      {
       "expr": "sum by(instance,pod,code) (rate(greptime_flow_errors[$__rate_interval]))",
       "legendFormat": "[{{instance}}]-[{{pod}}]-[{{code}}]"
      }
     ]
    }
   ]
  }
 ]
}