{
 "title": "GreptimeDB Flownode",
 "description": "The Grafana dashboard of GreptimeDB flownode.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Flownode APIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flow Ingest / Output Rate",
   "type": "timeseries",
   "description": "Flow Ingest / Output Rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance, pod, direction) (rate(greptime_flow_processed_rows[$__rate_interval]))",
     "legendFormat": "[{{pod}}]-[{{instance}}]-[{{direction}}]"
    }
   ]
  },
  {
   "title": "Flow Ingest Latency",
   "type": "timeseries",
   "description": "Flow Ingest Latency.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(greptime_flow_insert_elapsed_bucket[$__rate_interval])) by (le, instance, pod))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(greptime_flow_insert_elapsed_bucket[$__rate_interval])) by (le, instance, pod))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-p99"
    }
   ]
  },
  {
   "title": "Flow Operation Latency",
   "type": "timeseries",
   "description": "Flow Operation Latency.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(greptime_flow_processing_time_bucket[$__rate_interval])) by (le,instance,pod,type))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{type}}]-p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(greptime_flow_processing_time_bucket[$__rate_interval])) by (le,instance,pod,type))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{type}}]-p99"
    }
   ]
  },
  {
   "title": "Flow Buffer Size per Instance",
   "type": "timeseries",
   "description": "Flow Buffer Size per Instance.",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "targets": [
    { "expr": "greptime_flow_input_buf_size", "legendFormat": "[{{instance}}]-[{{pod}]" }
   ]
  },
  {
   "title": "Flow Processing Error per Instance",
   "type": "timeseries",
   "description": "Flow Processing Error per Instance.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum by(instance,pod,code) (rate(greptime_flow_errors[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{code}}]"
    }
   ]
  }
 ]
}