{
 "title": "GreptimeDB Frontend",
 "description": "The Grafana dashboard of GreptimeDB frontend.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   {
    "name": "frontend",
    "query": {
     "query": "label_values(greptime_app_version{app=\"greptime-frontend\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP QPS per Instance",
   "type": "timeseries",
   "description": "HTTP QPS per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, path, method, code) (rate(greptime_servers_http_requests_elapsed_count{path!~\"/health|/metrics\"}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{path}}]-[{{method}}]-[{{code}}]"
    }
   ]
  },
  {
   "title": "HTTP P99 per Instance",
   "type": "timeseries",
   "description": "HTTP P99 per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, pod, le, path, method, code) (rate(greptime_servers_http_requests_elapsed_bucket{path!~\"/health|/metrics\"}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{path}}]-[{{method}}]-[{{code}}]-p99"
    }
   ]
  },
  {
   "title": "gRPC QPS per Instance",
   "type": "timeseries",
   "description": "gRPC QPS per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, path, code) (rate(greptime_servers_grpc_requests_elapsed_count{}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{path}}]-[{{code}}]"
    }
   ]
  },
  {
   "title": "gRPC P99 per Instance",
   "type": "timeseries",
   "description": "gRPC P99 per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, pod, le, path, code) (rate(greptime_servers_grpc_requests_elapsed_bucket{}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{path}}]-[{{method}}]-[{{code}}]-p99"
    }
   ]
  },
  {
   "title": "MySQL QPS per Instance",
   "type": "timeseries",
   "description": "MySQL QPS per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod, instance)(rate(greptime_servers_mysql_query_elapsed_count{}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]"
    }
   ]
  },
  {
   "title": "MySQL P99 per Instance",
   "type": "timeseries",
   "description": "MySQL P99 per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, instance, le) (rate(greptime_servers_mysql_query_elapsed_bucket{}[$__rate_interval])))",
     "legendFormat": "[{{ instance }}]-[{{ pod }}]-p99"
    }
   ]
  },
  {
   "title": "PostgreSQL QPS per Instance",
   "type": "timeseries",
   "description": "PostgreSQL QPS per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod, instance)(rate(greptime_servers_postgres_query_elapsed_count{}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]"
    }
   ]
  },
  {
   "title": "PostgreSQL P99 per Instance",
   "type": "timeseries",
   "description": "PostgreSQL P99 per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod,instance,le) (rate(greptime_servers_postgres_query_elapsed_bucket{}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-p99"
    }
   ]
  },
  { "title": "Frontend to Datanode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Region Call QPS per Instance",
   "type": "timeseries",
   "description": "Region Call QPS per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance, pod, request_type) (rate(greptime_grpc_region_request_count{}[$__rate_interval]))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{request_type}}]"
    }
   ]
  },
  {
   "title": "Region Call P99 per Instance",
   "type": "timeseries",
   "description": "Region Call P99 per Instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(instance, pod, le, request_type) (rate(greptime_grpc_region_request_bucket{}[$__rate_interval])))",
     "legendFormat": "[{{instance}}]-[{{pod}}]-[{{request_type}}]"
    }
   ]
  }
 ]
}