{
 "title": "GreptimeDB Metasrv",
 "description": "The Grafana dashboard of GreptimeDB metasrv.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   {
    "name": "metasrv",
    "query": {
     "query": "label_values(greptime_app_version{app=\"greptime-metasrv\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Metasrv", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Region migration datanode",
   "type": "state-timeline",
   "description": "Counter of region migration by source and destination",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "greptime_meta_region_migration_stat{datanode_type=\"src\"}",
     "legendFormat": "from-datanode-{{datanode_id}}"
    },
    {
     "expr": "greptime_meta_region_migration_stat{datanode_type=\"desc\"}",
     "legendFormat": "to-datanode-{{datanode_id}}"
    }
   ]
  },
  {
   "title": "Region migration error",
   "type": "timeseries",
   "description": "Counter of region migration error",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "greptime_meta_region_migration_error",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datanode load",
   "type": "timeseries",
   "description": "Gauge of load information of each datanode, collected via heartbeat between datanode and metasrv. This information is for metasrv to schedule workloads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "greptime_datanode_load", "legendFormat": "__auto" }
   ]
  }
 ]
}