{
 "title": "GreptimeDB Overview",
 "description": "The overview of GreptimeDB.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "information_schema", "query": "mysql" },
   {
    "name": "datanode",
    "query": {
     "query": "label_values(greptime_app_version{app=\"greptime-datanode\"},instance)"
    }
   },
   {
    "name": "frontend",
    "query": {
     "query": "label_values(greptime_app_version{app=\"greptime-frontend\"},instance)"
    }
   },
   {
    "name": "metasrv",
    "query": {
     "query": "label_values(greptime_app_version{app=\"greptime-metasrv\"},instance)"
    }
   },
   {
    "name": "flownode",
    "query": {
     "query": "label_values(greptime_app_version{app=\"greptime-flownode\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The start time of GreptimeDB.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "GreptimeDB version.",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT pkg_version FROM information_schema.build_info"
    }
   ]
  },
  {
   "title": "Total Ingestion Rate",
   "type": "stat",
   "description": "Total ingestion rate.",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(greptime_table_operator_ingest_rows[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Storage Size",
   "type": "stat",
   "description": "Total number of data file size.",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "select SUM(disk_size) from information_schema.region_statistics;"
    }
   ]
  },
  {
   "title": "Total Rows",
   "type": "stat",
   "description": "Total number of data rows in the cluster. Calculated by sum of rows from each region.",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "select SUM(region_rows) from information_schema.region_statistics;"
    }
   ]
  },
  {
   "title": "Deployment",
   "type": "stat",
   "description": "The deployment topology of GreptimeDB.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT count(*) as datanode FROM information_schema.cluster_info WHERE peer_type = 'DATANODE';"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT count(*) as frontend FROM information_schema.cluster_info WHERE peer_type = 'FRONTEND';"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT count(*) as metasrv FROM information_schema.cluster_info WHERE peer_type = 'METASRV';"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT count(*) as flownode FROM information_schema.cluster_info WHERE peer_type = 'FLOWNODE';"
    }
   ]
  },
  {
   "title": "Data",
   "type": "stat",
   "description": "The number of the key resources in GreptimeDB.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "information_schema",
     "rawSql": "SELECT COUNT(*) as databases FROM information_schema.schemata WHERE schema_name NOT IN ('greptime_private', 'information_schema')"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT COUNT(*) as tables FROM information_schema.tables WHERE table_schema != 'information_schema'"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT COUNT(region_id) as regions FROM information_schema.region_peers"
    },
    {
     "dataset": "information_schema",
     "rawSql": "SELECT COUNT(*) as flows FROM information_schema.flows"
    }
   ]
  },
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Ingestion Rate",
   "type": "timeseries",
   "description": "Total ingestion rate.\n\nHere we listed 3 primary protocols:\n\n- Prometheus remote write\n- Greptime's gRPC API (when using our ingest SDK)\n- Log ingestion http API\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(rate(greptime_table_operator_ingest_rows{}[$__rate_interval]))",
     "legendFormat": "ingestion"
    }
   ]
  },
  {
   "title": "Ingestion Rate by Type",
   "type": "timeseries",
   "description": "Total ingestion rate.\n\nHere we listed 3 primary protocols:\n\n- Prometheus remote write\n- Greptime's gRPC API (when using our ingest SDK)\n- Log ingestion http API\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(rate(greptime_servers_http_logs_ingestion_counter[$__rate_interval]))",
     "legendFormat": "http-logs"
    },
    {
     "expr": "sum(rate(greptime_servers_prometheus_remote_write_samples[$__rate_interval]))",
     "legendFormat": "prometheus-remote-write"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total Query Rate",
   "type": "timeseries",
   "description": "Total rate of query API calls by protocol. This metric is collected from frontends.\n\nHere we listed 3 main protocols:\n- MySQL\n- Postgres\n- Prometheus API\n\nNote that there are some other minor query APIs like /sql are not included",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(greptime_servers_mysql_query_elapsed_count{}[$__rate_interval]))",
     "legendFormat": "mysql"
    },
    {
     "expr": "sum (rate(greptime_servers_postgres_query_elapsed_count{}[$__rate_interval]))",
     "legendFormat": "pg"
    },
    {
     "expr": "sum (rate(greptime_servers_http_promql_elapsed_counte{}[$__rate_interval]))",
     "legendFormat": "promql"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Datanode Memory per Instance",
   "type": "timeseries",
   "description": "Current memory usage by instance",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{}) by (instance, pod)",
     "legendFormat": "[{{instance}}]-[{{ pod }}]"
    }
   ]
  },
  {
   "title": "Datanode CPU Usage per Instance",
   "type": "timeseries",
   "description": "Current cpu usage by instance",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{}[$__rate_interval]) * 1000) by (instance, pod)",
     "legendFormat": "[{{ instance }}]-[{{ pod }}]"
    }
   ]
  },
  {
   "title": "Frontend Memory per Instance",
   "type": "timeseries",
   "description": "Current memory usage by instance",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{}) by (instance, pod)",
     "legendFormat": "[{{ instance }}]-[{{ pod }}]"
    }
   ]
  },
  {
   "title": "Frontend CPU Usage per Instance",
   "type": "timeseries",
   "description": "Current cpu usage by instance",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{}[$__rate_interval]) * 1000) by (instance, pod)",
     "legendFormat": "[{{ instance }}]-[{{ pod }}]-cpu"
    }
   ]
  },
  {
   "title": "Metasrv Memory per Instance",
   "type": "timeseries",
   "description": "Current memory usage by instance",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{}) by (instance, pod)",
     "legendFormat": "[{{ instance }}]-[{{ pod }}]-resident"
    }
   ]
  },
  {
   "title": "Metasrv CPU Usage per Instance",
   "type": "timeseries",
   "description": "Current cpu usage by instance",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{}[$__rate_interval]) * 1000) by (instance, pod)",
     "legendFormat": "[{{ instance }}]-[{{ pod }}]"
    }
   ]
  },
  {
   "title": "Flownode Memory per Instance",
   "type": "timeseries",
   "description": "Current memory usage by instance",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{}) by (instance, pod)",
     "legendFormat": "[{{ instance }}]-[{{ pod }}]"
    }
   ]
  },
  {
   "title": "Flownode CPU Usage per Instance",
   "type": "timeseries",
   "description": "Current cpu usage by instance",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{}[$__rate_interval]) * 1000) by (instance, pod)",
     "legendFormat": "[{{ instance }}]-[{{ pod }}]"
    }
   ]
  }
 ]
}