-- Dynamic Filter Test: TopK (Sort + Limit)
-- Tests dynamic filters generated by TopK operator

-- Test 2.1: Basic TopK
CREATE TABLE orders ("id" INT, customer_id INT, amount DOUBLE, ts TIMESTAMP TIME INDEX);

-- Insert sufficient test data
INSERT INTO orders VALUES
  (1, 1, 100.0, '2024-01-01 00:00:00'),
  (2, 2, 200.0, '2024-01-02 00:00:00'),
  (3, 3, 300.0, '2024-01-03 00:00:00'),
  (4, 1, 150.0, '2024-01-04 00:00:00'),
  (5, 2, 250.0, '2024-01-05 00:00:00'),
  (6, 1, 175.0, '2024-01-06 00:00:00'),
  (7, 3, 325.0, '2024-01-07 00:00:00'),
  (8, 2, 225.0, '2024-01-08 00:00:00');

-- Test: Basic TopK query - get top 3 orders by amount
-- TopK (Sort + Limit) should generate dynamic filter on amount
EXPLAIN SELECT "id", customer_id, amount
FROM orders
ORDER BY amount DESC
LIMIT 3;

-- SQLNESS REPLACE (-+) -
-- SQLNESS REPLACE (\s\s+) _
-- SQLNESS REPLACE (peers.*) REDACTED
-- SQLNESS REPLACE (metrics.*) REDACTED
EXPLAIN ANALYZE SELECT "id", customer_id, amount
FROM orders
ORDER BY amount DESC
LIMIT 3;

-- Verify correctness
SELECT "id", customer_id, amount
FROM orders
ORDER BY amount DESC
LIMIT 3;

DROP TABLE orders;

-- Test 2.2: TopK with Projection Alias
-- USER NOTE: must make alias for topk's sort column to be able to test dynamic filter pushdown
CREATE TABLE orders ("id" INT, customer_id INT, amount DOUBLE, ts TIMESTAMP TIME INDEX);

-- Insert test data
INSERT INTO orders VALUES
  (1, 1, 100.0, '2024-01-01 00:00:00'),
  (2, 2, 200.0, '2024-01-02 00:00:00'),
  (3, 3, 300.0, '2024-01-03 00:00:00'),
  (4, 1, 150.0, '2024-01-04 00:00:00'),
  (5, 2, 250.0, '2024-01-05 00:00:00'),
  (6, 1, 175.0, '2024-01-06 00:00:00'),
  (7, 3, 325.0, '2024-01-07 00:00:00'),
  (8, 2, 225.0, '2024-01-08 00:00:00');

-- Test: TopK with projection alias
-- The alias on amount tests that dynamic filter correctly handles column references after projection
EXPLAIN SELECT "id", customer_id, total_amount
FROM (SELECT "id", customer_id, amount as total_amount, ts FROM orders)
ORDER BY total_amount DESC
LIMIT 3;

-- SQLNESS REPLACE (-+) -
-- SQLNESS REPLACE (\s\s+) _
-- SQLNESS REPLACE (peers.*) REDACTED
-- SQLNESS REPLACE (metrics.*) REDACTED
EXPLAIN ANALYZE SELECT "id", customer_id, total_amount
FROM (SELECT "id", customer_id, amount as total_amount, ts FROM orders)
ORDER BY total_amount DESC
LIMIT 3;

-- Verify correctness
SELECT "id", customer_id, total_amount
FROM (SELECT "id", customer_id, amount as total_amount, ts FROM orders)
ORDER BY total_amount DESC
LIMIT 3;

DROP TABLE orders;
