--- test information_schema.table_constraints ----

USE INFORMATION_SCHEMA;

DESC TABLE TABLE_CONSTRAINTS;

SELECT * FROM TABLE_CONSTRAINTS ORDER BY TABLE_NAME, CONSTRAINT_NAME;

CREATE TABLE test(i double, j string, ts timestamp time index, primary key(j));

SELECT * FROM TABLE_CONSTRAINTS ORDER BY TABLE_NAME, CONSTRAINT_NAME;

SELECT * FROM TABLE_CONSTRAINTS WHERE TABLE_NAME = 'test' ORDER BY TABLE_NAME, CONSTRAINT_NAME;

DROP TABLE test;

USE public;
