name: Setup Chaos Mesh
description: Install and wait for Chaos Mesh
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - name: Install Chaos Mesh
    shell: bash
    run: |
      helm repo add chaos-mesh https://charts.chaos-mesh.org
      helm repo update chaos-mesh
      kubectl create ns chaos-mesh
      helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-mesh --version 2.6.3
  - name: Print Chaos-mesh
    if: always()
    shell: bash
    run: | 
      kubectl get po -n chaos-mesh
