on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'docs/**'
      - 'config/**'
      - '**.md'
      - '.dockerignore'
      - 'docker/**'
      - '.gitignore'
      - 'grafana/**'
      - 'Makefile'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'config/**'
      - '**.md'
      - '.dockerignore'
      - 'docker/**'
      - '.gitignore'
      - 'grafana/**'
      - 'Makefile'
  workflow_dispatch:

name: Docs CI

# To pass the required status check, see:
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: crate-ci/typos@master

  license-header-check:
    runs-on: ubuntu-latest
    name: Check License Header
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: korandoru/hawkeye@v5

  required-checks:
    name: ${{ matrix.check }}
    runs-on: ubuntu-slim
    strategy:
      matrix:
        check:
          - Check
          - Rustfmt
          - Clippy
          - Unused Dependencies
          - Sqlness Test (Basic)
          - Sqlness Test (Remote WAL)
          - test
          - coverage
          - Sqlness Test (Flat format)
          - Compatibility Test (recent releases)
    steps:
      - run: 'echo "No action required"'
